name: Node.js CI

on: [push]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - name: Installing dependencies
        run: pnpm install
      - name: Linting
        run: pnpm lint
      - name: Type checking
        run: pnpm typecheck
      - name: Testing
        run: pnpm coverage
      - name: Building
        run: pnpm build
